web:
  build: .
  volumes:
   - .:/src
  command:  nodemon -e js --harmony-async-await index.js
  environment:
    NODE_ENV: dev
    VIRTUAL_HOST: 'counter.local.dev'
    VIRTUAL_PORT: 8080
  external_links:
   - mysql